#!/bin/bash

CORE=../../js

cp $CORE/library/tcrypt.js data/
cp $CORE/library/sjcl.js data/
cp $CORE/library/mootools-core-1.4.5.js data/

cp $CORE/images/site/icons/load_16x16.gif data/images
cp $CORE/images/favicon.128.png data/images
cp $CORE/images/favicon.png data/images

